name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: KGNET
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
