name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: KGNET
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kgnet"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "front-end"
          usedocker: true
