name: Build code for VM

on:
  push:
    branches: 
      - vm/new-container

jobs:
  build:
    name: KGNET
    runs-on: ubuntu-20.04
    timeout-minutes: 60

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          working-directory: ./front-end/
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300

